services:
  - type: web
    name: rag-mcq-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GEMINI_API_KEY
        sync: false # Cho phép đặt giá trị trong Render dashboard sau này 